### PR TITLE
Remove resource-intensive tests

### PR DESCRIPTION
**Pull request by pehamTom**
## Description

Sometimes the python tests for the state preparation synthesis fail due to a timeout in the optimal synthesis. This PR removes some of these costly tests.

## Checklist:

- [x] The pull request only contains commits that are related to it.
- [x] I have added appropriate tests and documentation.
- [x] I have made sure that all CI jobs on GitHub pass.
- [x] The pull request introduces no new warnings and follows the project's style guidelines.

### CODE REVIEW

**Review by burgholzer — COMMENTED** [review]
Just a quick side comment: should we really have (unit)tests that take up to 10 seconds and run them regularly on every pull request and push to main?

**Comment by pehamTom** [comment]
> Just a quick side comment: should we really have (unit)tests that take up to 10 seconds and run them regularly on every pull request and push to main?

I guess it is worse than that. It actually takes more than 10 seconds. However, this method ensures that the entire functionality is actually tested. I know how to speed this process up by parallelizing the asynchronous calls to the SAT solver, but I haven't gotten around to that yet. 

The alternative is to not test these instances, I guess.

**Comment by burgholzer** [comment]
Couldn't you "just" test smaller instances?
Coverage-wise, that should still result in roughly the same coverage, right?

**Comment by pehamTom** [comment]
@burgholzer now it should be better.

**Review by burgholzer — APPROVED** [review]
Looking good. Could be worth updating the PR title and description now though😉

**Pull request merged**
